const mongoose = require('mongoose');

const conflictSchema = new mongoose.Schema({
  type: {
    type: String,
    enum: ['docente', 'aula', 'estudiante', 'prerequisito', 'creditos', 'infraestructura'],
    required: true
  },
  description: String,
  severity: {
    type: String,
    enum: ['alta', 'media', 'baja'],
    default: 'media'
  }
}, { _id: false });

const generationSchema = new mongoose.Schema({
  name: {
    type: String,
    required: [true, 'El nombre de la generación es obligatorio'],
    trim: true
  },
  semester: {
    type: String,
    required: [true, 'El semestre es obligatorio']
  },
  status: {
    type: String,
    enum: ['programada', 'ejecutando', 'completada', 'fallida'],
    default: 'programada'
  },
  scheduledDate: {
    type: Date
  },
  executedAt: Date,
  completedAt: Date,
  executionTimeMs: Number,
  qualityScore: {
    type: Number,
    default: 0,
    min: 0,
    max: 100
  },
  constraintsFulfilled: {
    type: Number,
    default: 0,
    min: 0,
    max: 100
  },
  preferencesScore: {
    type: Number,
    default: 0,
    min: 0,
    max: 100
  },
  resourceUsage: {
    type: Number,
    default: 0,
    min: 0,
    max: 100
  },
  loadDistribution: {
    type: Number,
    default: 0,
    min: 0,
    max: 100
  },
  conflicts: [conflictSchema],
  // Alternatives generated by multi-solution CSP
  alternatives: [{
    scheduleId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Schedule'
    },
    qualityScore: { type: Number, default: 0 },
    preferencesScore: { type: Number, default: 0 },
    constraintsFulfilled: { type: Number, default: 0 },
    resourceUsage: { type: Number, default: 0 },
    optimization: { type: Number, default: 0 },
    label: { type: String, default: 'Alternativa' }
  }],
  // Conditions that could not be satisfied
  unsatisfiedConditions: [{
    condition: String,
    impact: { type: String, enum: ['Alto', 'Medio', 'Bajo'], default: 'Medio' },
    details: String,
    icon: String
  }],
  // Scoring breakdown
  scoringBreakdown: {
    validezHorario: { score: Number, weight: String, maxScore: Number },
    restriccionesInstitucionales: { score: Number, weight: String, maxScore: Number },
    preferenciasSatisfechas: { score: Number, weight: String, maxScore: Number },
    optimizacionGeneral: { score: Number, weight: String, maxScore: Number }
  },
  scheduleId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Schedule'
  },
  // Career-based generation
  career: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Career'
  },
  sectionsGenerated: {
    type: Number,
    default: 0
  },
  sectionWarnings: [{
    courseCode: String,
    courseName: String,
    warning: String,
    severity: { type: String, enum: ['info', 'warning', 'error'], default: 'warning' }
  }],
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }
}, {
  timestamps: true
});

generationSchema.index({ semester: 1, status: 1 });

module.exports = mongoose.model('Generation', generationSchema);
